# 交易系统配置文件

# 交易所API配置
exchange:
  name: "binance" # 交易所名称
  api_key: "mock_api_key_123"
  api_secret: "mock_api_secret_456"
  base_url: "https://api.binance.com"

# 区块链配置
blockchain:
  networks:
    - name: "ethereum"
      enabled: true
      rpc_url: "https://mainnet.infura.io/v3/your_infura_key"
      chain_id: 1
      gas_limit: 3000000
      gas_price: "auto" # 或固定值如 "20gwei"
    - name: "bsc"
      enabled: false
      rpc_url: "https://bsc-dataseed.binance.org/"
      chain_id: 56
      gas_limit: 3000000
      gas_price: "5gwei"
  contracts:
    trading_contract: "0x..." # 智能交易合约地址
    wallet_private_key: "4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d" # 测试用私钥

# 交易对设置
trading:
  pairs:
    - symbol: "BTC/USDT"
      enabled: true
    - symbol: "ETH/USDT"
      enabled: true
    - symbol: "ETH/BNB" # 区块链上的交易对
      enabled: true
      blockchain: "ethereum"
      contract_address: "0x..." # DEX上的交易对合约地址
  base_currency: "USDT"

# 策略参数
strategy:
  name: "moving_average_crossover" # 策略名称
  params:
    short_period: 5 # 短期移动平均线周期
    long_period: 20 # 长期移动平均线周期
    interval: "1h" # 数据时间间隔

# 风险控制参数
risk:
  max_position_size: 0.1 # 单个交易对最大仓位比例
  stop_loss: 0.05 # 止损比例
  take_profit: 0.1 # 止盈比例
  max_open_positions: 3 # 最大同时持仓数量
  max_gas_price: "100gwei" # 区块链交易最大gas价格
  slippage_tolerance: 0.5 # 滑点容忍度(%)

# 系统设置
system:
  log_level: "info" # 日志级别: debug, info, warn, error
  data_dir: "./data" # 数据存储目录
  backtest_mode: false # 是否为回测模式
  dapp_port: 3000 # DApp前端服务端口
